name: velixeo
publish_to: 'none'
description: VELIXEO bilingual digital services marketplace.
version: 0.14.7+41

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^7.2.0
  url_launcher: ^6.3.2
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  country_picker: ^2.0.28
  image_picker: ^1.2.0
  image_cropper: ^12.2.1
  font_awesome_flutter: ^11.0.0
  webview_flutter: ^4.13.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
